// Generated by gencpp from file robot_control/encoder_data.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_ENCODER_DATA_H
#define ROBOT_CONTROL_MESSAGE_ENCODER_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct encoder_data_
{
  typedef encoder_data_<ContainerAllocator> Type;

  encoder_data_()
    : left_encoder_data(0.0)
    , right_encoder_data(0.0)  {
    }
  encoder_data_(const ContainerAllocator& _alloc)
    : left_encoder_data(0.0)
    , right_encoder_data(0.0)  {
  (void)_alloc;
    }



   typedef double _left_encoder_data_type;
  _left_encoder_data_type left_encoder_data;

   typedef double _right_encoder_data_type;
  _right_encoder_data_type right_encoder_data;





  typedef boost::shared_ptr< ::robot_control::encoder_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::encoder_data_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_data_

typedef ::robot_control::encoder_data_<std::allocator<void> > encoder_data;

typedef boost::shared_ptr< ::robot_control::encoder_data > encoder_dataPtr;
typedef boost::shared_ptr< ::robot_control::encoder_data const> encoder_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::encoder_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::encoder_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control::encoder_data_<ContainerAllocator1> & lhs, const ::robot_control::encoder_data_<ContainerAllocator2> & rhs)
{
  return lhs.left_encoder_data == rhs.left_encoder_data &&
    lhs.right_encoder_data == rhs.right_encoder_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control::encoder_data_<ContainerAllocator1> & lhs, const ::robot_control::encoder_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_control::encoder_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::encoder_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::encoder_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::encoder_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::encoder_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::encoder_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::encoder_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8a513d02103e6ca180cd050ef8b19c8";
  }

  static const char* value(const ::robot_control::encoder_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8a513d02103e6caULL;
  static const uint64_t static_value2 = 0x180cd050ef8b19c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::encoder_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/encoder_data";
  }

  static const char* value(const ::robot_control::encoder_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::encoder_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# encoder_data.msg\n"
"\n"
"float64 left_encoder_data\n"
"float64 right_encoder_data\n"
;
  }

  static const char* value(const ::robot_control::encoder_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::encoder_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_encoder_data);
      stream.next(m.right_encoder_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::encoder_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::encoder_data_<ContainerAllocator>& v)
  {
    s << indent << "left_encoder_data: ";
    Printer<double>::stream(s, indent + "  ", v.left_encoder_data);
    s << indent << "right_encoder_data: ";
    Printer<double>::stream(s, indent + "  ", v.right_encoder_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_ENCODER_DATA_H
